FROM quay.io/keycloak/keycloak:26.5.0

ENV KC_HEALTH_ENABLED="true"
ENV KC_METRICS_ENABLED="true"
ENV KC_LOG_LEVEL="INFO"


WORKDIR /opt/keycloak


COPY --chown=keycloak:keycloak ./keycloak/providers/*.jar /opt/keycloak/providers/


RUN /opt/keycloak/bin/kc.sh build --db=mysql --features=scripts,token-exchange,admin-fine-grained-authz

